"#    #       #   #           #      
"#       ##      ###     # #     ### 
"#    #  # #  #   #      # #  #  ### 
"#    ## # #  ##  ##      #   ## # #


"set relativenumber
set number
set showtabline=2
set cursorline


filetype plugin on
syntax on




if has('nvim') || has('termguicolors')
"set termguicolors
endif


"let g:nord_cursor_line_number_background = 1
"highlight cursor
"set cursorcolumn
hi Normal ctermbg=NONE
highlight CursorLineNr cterm=NONE ctermfg=Red ctermbg=NONE
highlight LineNr cterm=NONE ctermfg=Black ctermbg=NONE
set laststatus=0
set noshowmode

"set noruler

" airline
let g:bufferline_echo = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme="iceberDark"


"if empty(glob('~/.vim/autoload/plug.vim'))
"  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
"    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
"endif


call plug#begin('~/.vim/plugged')
Plug 'NLKNguyen/papercolor-theme'
Plug 'dylanaraps/wal.vim'
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
Plug 'gkeep/iceberg-dark'
Plug 'pacha/vem-dark' 
Plug 'pacha/vem-tabline' 
Plug 'pacha/vem-statusline' 
Plug 'shime/vim-livedown'
Plug 'challenger-deep-theme/vim', { 'as': 'challenger-deep' }
Plug 'vim-airline/vim-airline-themes'
Plug 'nightsense/snow'
Plug 'mhinz/vim-startify'
Plug 'arcticicestudio/nord-vim'
Plug 'bling/vim-bufferline'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
call plug#end()


colorscheme iceberg


if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif


"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  set termguicolors
endif


"bspwm color border:
if $DISPLAY != ""
	autocmd FocusGained * :silent execute "!$HOME/.vim/bspwm_border_color/set " . shellescape(mode())
	autocmd InsertEnter * :silent execute "!$HOME/.vim/bspwm_border_color/set i"
	autocmd InsertLeave * :silent execute "!$HOME/.vim/bspwm_border_color/set n"
	autocmd VimLeave * :silent !$HOME/.vim/bspwm_border_color/reset
	set title titlestring=VIM "So the listener script can tell its a VIM window
endif


"if filereadable(expand("~/.vimrc_background"))
"  let base16colorspace=256
"  source ~/.vimrc_background
"endif
