#! /bin/sh

sxhkd &
tint3 &
compton &
nitrogen --restore 
network-manager-applet & 

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         2
bspc config window_gap           4
bspc config top_padding         25
bspc config focused_border_color  "#da0045"
bspc config normal_border_color   "#111313"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
