#! /bin/sh

# autostart some shit
sxhkd &
compton &
#dunst &
dunst -conf ~/.config/dunst/dunstrc &
feh --bg-scale Bilder/wp/termtor.jpg
$HOME/.config/polybar/launch.sh


bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d www trm fls mpd pht cds rdt trnt cht 10

bspc config border_width        8 
bspc config window_gap          0 

## pywal
## source the colors.
. "${HOME}/.cache/wal/colors.sh"

## Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

# Set the border colors
bspc config normal_border_color "#0e0e10"
bspc config active_border_color "#08090A"
bspc config focused_border_color "##3A768E"
bspc config presel_feedback_color "#151515"

bspc config split_ratio          0.50
bspc config single_monocle  true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config center_pseudo_tiled true

# Automatic Splitting Settings
bspc config automatic_scheme	longest_side
bspc config initial_polarity	second_child

bspc config top_padding 41 
#bspc config bottom_padding 10 
#bspc config left_padding 10
#bspc config right_padding 10

bspc rule --add Firefox desktop=I focus=on 
bspc rule --add Thunar desktop=III follow=off 
bspc rule --add Transmission-gtk desktop=VIII follow=off 
bspc rule --add 'Termite -e weechat' desktop=IX follow=on
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a transmission desktop='^8' 
