#! /bin/sh
#
#   #                           
#   ###  ## ### # # ### ### ### 
#   # #  #  # # ### ### #   #   
#   ### ##  ### ### # # #   ###
#           #
#

# Autostart Some Shit
sxhkd &
picom &
dunst &
$HOME/.config/polybar/launch.sh

# Wallpaper
#hsetroot -solid '#111113' &
#feh --bg-fill ~/Bider/wp/joker.png &
#bwall &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4 
bspc config window_gap   0 


# Set the border colors - without pywal
bspc config normal_border_color "#262727"
bspc config active_border_color "#7CABA3"
bspc config focused_border_color "#BFBFBF"
bspc config presel_feedback_color "#101113"


bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_follows_focus false
bspc config ignore_ewmh_focus true
bspc config center_pseudo_tiled true
bspc config split_ratio          0.50

# Automatic Splitting Settings
bspc config automatic_scheme	spiral
bspc config initial_polarity	second_child

# Leave Room For Panel
bspc config top_padding 32
#bspc config bottom_padding 10 
#bspc config left_padding 10
#bspc config right_padding 10

# Some personal rules
bspc rule --add firefox desktop=I follow=off 
bspc rule --add qutebrowser desktop=I follow=off
bspc rule --add Opera desktop=I follow=off
bspc rule --add Thunar desktop=III follow=off 

bspc rule --add Zathura state=tiled
bspc rule --add TelegramDesktop desktop=II focus=off follow=off
bspc rule --add Transmission-gtk desktop=VIII focus=off follow=off
bspc rule --add feh state=floating focus=on
bspc rule --add mpv state=floating

function reset_color_if_not_VIM {
	#autocmd events in ~/.vimrc will handle case where window is VIM
	node_id=$(echo $1 | grep -oE '[^ ]+$')
	node_name=$(xtitle $node_id)
	if [[ $node_name != *"VIM"* ]]; then
		$HOME/.vim/bspwm_border_color/reset
	fi
}
bspc subscribe node_focus | while read -r line; do reset_color_if_not_VIM "$line"; done

# vim: ft=sh
