#! /bin/sh
#
#   #                           
#   ###  ## ### # # ### ### ### 
#   # #  #  # # ### ### #   #   
#   ### ##  ### ### # # #   ###
#           #
#

# Autostart Some Shit
sxhkd &
picom &
dunst &
$HOME/.config/polybar/launch.sh & 

#$HOME/.config/bspwm/scripts/borderless &

# Wallpaper
#hsetroot -solid '#4d5a60' &
feh --bg-tile Bilder/wp/escher.png


# bitmap fonts
xset +fp ~/.local/share/fonts &
xset fp rehash &
xset fp+ /usr/share/fonts/bitmap &

bspc monitor -d  I II III IV V VI VII VIII IX X

#bspc monitor -d I 
#bspc monitor DP2-1 II III IV 
#bspc monitor DP2-2 V VI VII
#bspc monitor DVI VIII IX X

# appearance  
bspc config border_width 8
bspc config window_gap   32 

#bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-gap)) 30
#bspc config left_padding -$gap
#bspc config right_padding -$gap
#bspc config bottom_padding -$gap

# Set the border colors - without pywal
# Dracula
#bspc config normal_border_color "#282a36"
#bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#BFBFBF"
#bspc config presel_feedback_color "#6272a4"

# ICEBERG
bspc config normal_border_color "#1c1c1c"
bspc config active_border_color "#7CABA3"
bspc config focused_border_color "#777777"
bspc config presel_feedback_color "#3a3a3a"

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config center_pseudo_tiled true
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.50

# Automatic Splitting Settings
bspc config automatic_scheme	spiral
bspc config initial_polarity	second_child


# Some personal rules
bspc rule --add firefox desktop=I follow=off 
bspc rule --add qutebrowser desktop=I follow=off
bspc rule --add Opera desktop=I follow=off
bspc rule --add Google-chrome desktop=I follow=off
bspc rule --add TelegramDesktop desktop=II follow=off
bspc rule --add Thunar desktop=III follow=off 
bspc rule --add Zathura state=tiled
bspc rule --add Transmission-gtk desktop=VIII focus=off follow=on
bspc rule --add feh state=floating focus=on
bspc rule --add mpv state=floating


function reset_color_if_not_VIM {
	#autocmd events in ~/.vimrc will handle case where window is VIM
	node_id=$(echo $1 | grep -oE '[^ ]+$')
	node_name=$(xtitle $node_id)
	if [[ $node_name != *"VIM"* ]]; then
		$HOME/.vim/bspwm_border_color/reset
	fi
}

bspc subscribe node_focus | while read -r line; do reset_color_if_not_VIM "$line"; done



# vim: ft=sh
